// src/pages/Rust.svelte
<script>
  import { t } from '../i18n.js'
  import { navigate } from 'svelte-routing'

  function goTo(path, e) {
    e.preventDefault()
    navigate(path)
  }
</script>

<div class="page">
  <a href="/fun" class="back-link" on:click={(e) => goTo('/fun', e)}>
    ← {$t('back')}
  </a>
  <h1 class="page-title">{$t('rust.title')}</h1>
  <p class="page-desc">{$t('rust.description')}</p>
</div>

<style>
</style>

// src/pages/Rust/Rust.jsx
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import './Rust.css'

export default function Rust() {
  const { t } = useTranslation()

  return (
    <div className="page">
      <Link to="/fun" className="back-link">← {t('back')}</Link>
      <h1 className="page-title">{t('rust.title')}</h1>
      <p className="page-desc">{t('rust.description')}</p>
    </div>
  )
}
